version: '3.8'
services:
  gateway:
    build: gateway/
    container_name: gateway
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server/
    container_name: server
    depends_on:
      - db
    ports:
      - "9090:9090"
      - "9091:9091"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME =test
      - SPRING_DATASOURCE_PASSWORD =test


  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      PGDATA: /home/aleksandr/dev/add-docker/java-shareit-add-docker
    volumes:
        - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
