create sequence IF NOT EXISTS hibernate_sequence start with 1 increment by 1;
create TABLE IF NOT EXISTS users (
user_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
name VARCHAR(255) NOT NULL,
email VARCHAR(512) NOT NULL UNIQUE,
CONSTRAINT pk_user PRIMARY KEY (user_id)
);

create TABLE IF NOT EXISTS items_booking(
booking_id bigint,
item_id bigint,
CONSTRAINT items_booking1 PRIMARY KEY (booking_id,item_ID)
);


CREATE TABLE IF NOT EXISTS requests(
request_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
description VARCHAR(128) NOT NULL,
date_created timestamptz NOT NULL,
user_id bigint NOT NULL,
CONSTRAINT pk_requests PRIMARY KEY (request_id)
);

create TABLE IF NOT EXISTS booking (
booking_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
start_date timestamptz NOT NULL,
end_date timestamptz NOT NULL,
booker_id bigint,
item_id bigint NOT NULL,
status VARCHAR(31),
CONSTRAINT pk_booking PRIMARY KEY (booking_id)
);

create TABLE IF NOT EXISTS comments (
comment_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
booker_id bigint,
item_id bigint NOT NULL,
text VARCHAR(511),
date_comment timestamptz NOT NULL,
CONSTRAINT pk_reviews PRIMARY KEY (comment_id)
);

create TABLE IF NOT EXISTS items (
item_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
owner_id bigint NOT NULL,
name VARCHAR(255) NOT NULL,
description VARCHAR(512) NOT NULL,
available BOOLEAN NOT NULL,
next_booking_id bigint,
last_booking_id bigint,
request_id bigint,
CONSTRAINT pk_items PRIMARY KEY (item_id)
);
ALTER TABLE items_booking DROP CONSTRAINT IF EXISTS FK_booking_item;
ALTER TABLE items_booking ADD CONSTRAINT FK_booking_item FOREIGN KEY (item_id)  REFERENCES items (item_id);
ALTER TABLE items_booking DROP CONSTRAINT IF EXISTS FK_booking;
ALTER TABLE items_booking ADD CONSTRAINT FK_booking FOREIGN KEY (booking_id)  REFERENCES booking (booking_id);
ALTER TABLE COMMENTS DROP CONSTRAINT IF EXISTS FK_COMMENTS_booker;
ALTER TABLE COMMENTS ADD CONSTRAINT FK_COMMENTS_booker FOREIGN KEY (booker_id)  REFERENCES users (user_id );
ALTER TABLE ITEMS DROP CONSTRAINT IF EXISTS FK_item_user;
ALTER TABLE ITEMS ADD CONSTRAINT  FK_item_user FOREIGN KEY (OWNER_ID)  REFERENCES users (user_id );

