create sequence IF NOT EXISTS hibernate_sequence start with 1 increment by 1;
create TABLE IF NOT EXISTS users (
user_id Long GENERATED BY DEFAULT AS IDENTITY NOT NULL,
name VARCHAR(255) NOT NULL,
email VARCHAR(512) NOT NULL UNIQUE,
CONSTRAINT pk_user PRIMARY KEY (user_id)
);

create TABLE IF NOT EXISTS items_booking(
booking_id Long,
item_id Long,
CONSTRAINT items_booking PRIMARY KEY (booking_id,item_ID)
);


CREATE TABLE IF NOT EXISTS requests(
request_id long GENERATED BY DEFAULT AS IDENTITY NOT NULL,
description VARCHAR(128) NOT NULL,
date_created datetime NOT NULL,
user_id long NOT NULL,
CONSTRAINT pk_requests PRIMARY KEY (request_id)
);

create TABLE IF NOT EXISTS booking (
booking_id Long GENERATED BY DEFAULT AS IDENTITY NOT NULL,
start_date datetime NOT NULL,
end_date datetime NOT NULL,
booker_id Long,
item_id Long NOT NULL,
status VARCHAR(31),
CONSTRAINT pk_booking PRIMARY KEY (booking_id)
);

create TABLE IF NOT EXISTS comments (
comment_id Long GENERATED BY DEFAULT AS IDENTITY NOT NULL,
booker_id Long,
item_id Long NOT NULL,
text VARCHAR(511),
date_comment datetime NOT NULL,
CONSTRAINT pk_reviews PRIMARY KEY (comment_id)
);

create TABLE IF NOT EXISTS items (
item_id Long GENERATED BY DEFAULT AS IDENTITY NOT NULL,
owner_id Long NOT NULL,
name VARCHAR(255) NOT NULL,
description VARCHAR(512) NOT NULL,
available BOOLEAN NOT NULL,
next_booking_id long,
last_booking_id long,
request_id long,
CONSTRAINT pk_items PRIMARY KEY (item_id)
);

ALTER TABLE items_booking ADD CONSTRAINT IF NOT EXISTS  FK_booking_item FOREIGN KEY (item_id)  REFERENCES items (item_id);
ALTER TABLE items_booking ADD CONSTRAINT IF NOT EXISTS  FK_booking FOREIGN KEY (booking_id)  REFERENCES booking (booking_id);
ALTER TABLE COMMENTS ADD CONSTRAINT IF NOT EXISTS  FK_COMMENTS_booker FOREIGN KEY (booker_id)  REFERENCES users (user_id );
ALTER TABLE ITEMS ADD CONSTRAINT IF NOT EXISTS  FK_item_user FOREIGN KEY (OWNER_ID)  REFERENCES users (user_id );

